// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("rescript/lib/js/caml_obj.js");

var a = {
  foo: "bar"
};

var b = {
  foo: "bar"
};

function fn() {
  return Caml_obj.equal(a, b);
}

exports.a = a;
exports.b = b;
exports.fn = fn;
/* No side effect */
