// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as DataMjs from "./data.mjs";

var one = DataMjs.one;

var two = DataMjs.two;

function compareLargeObjects() {
  Caml_obj.equal(one, two);
}

export {
  one ,
  two ,
  compareLargeObjects ,
}
/* one Not a pure module */
