// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as SmallDataMjs from "./small-data.mjs";

var one = SmallDataMjs.one;

var two = SmallDataMjs.two;

function compareSmallObjects() {
  if (Caml_obj.equal(one, two) === true) {
    console.error("Values match when they should not");
  }
  if (Caml_obj.equal(one, one) === false) {
    console.error("one Values did not match when they should");
  }
  if (Caml_obj.equal(Object.assign({}, one), Object.assign({}, one)) === false) {
    console.error("two Values did not match when they should");
    return ;
  }
  
}

export {
  one ,
  two ,
  compareSmallObjects ,
}
/* one Not a pure module */
